### ISSUE TITLE
Not Working in Firefox 56 on Linux

### ISSUE THREAD

**Issue by MichaelTunnell** [def00111/copy-link-text#1]
The context menu is there but when used it doesn't send anything to my clipboard.

Firefox 57
KDE Neon (Ubuntu 16.04 / Linux)

**Comment by Whisprin** [comment]
Same here on Firefox 56.0.1 (stable) and 58.0a1 (nightly, 2017-10-15).

However, the older extension "Copy Link Title" does work.

**Comment by def00111** [comment]
@Whisprin you also have Linux?
@MichaelTunnell you need to wait for this bug to be fixed: https://bugzilla.mozilla.org/show_bug.cgi?id=1357487

**Comment by Whisprin** [comment]
@def00111 Yes, Linux.

Setting `extensions.webextensions.remote` to `true` in about:config did the trick. This extension works now.

What are the differences between Copy Link Title and this extension? Both are web extensions but only one of them works out of the box.

**Comment by MichaelTunnell** [comment]
>  @MichaelTunnell you need to wait for this bug to be fixed: https://bugzilla.mozilla.org/show_bug.cgi?id=1357487

The issue though is that it used to work in Firefox 55 and I think in 56 for a short while and then it stopped working.

> Setting extensions.webextensions.remote to true in about:config did the trick. This extension works now.

Thanks for that and if that is the case then that shows there was a regression.

> Both are web extensions but only one of them works out of the box.

this issue for me was that it did used to work out of the box.

**Comment by def00111** [comment]
> What are the differences between Copy Link Title and this extension? Both are web extensions but only one of them works out of the box.

Copy Link Title is an old extension.

**Comment by acmodeu** [comment]
The extension seems not to be working on Windows 8.1, Firefox 56.0.1 x64 either. Should I open another thread for it?

**Comment by def00111** [comment]
@acmodeu you have `extensions.webextensions.remote` set to true?

The add-on works fine for me in Windows 10.

**Comment by acmodeu** [comment]
Yes, but it doesn't do the trick.

**Comment by def00111** [comment]
https://github.com/def00111/copy-link-text/commit/8c90013586ab0e96be29ddf61f8095e89b768722 should fix this.

**Comment by Whisprin** [comment]
@def00111 I can confirm that it's working now. Even with `extensions.webextensions.remote` set to `false` (default).

**Comment by def00111** [comment]
But it will not work if you set the pref "dom.event.clipboardevents.enabled" to false:
https://bugzilla.mozilla.org/show_bug.cgi?id=1396275

**Comment by grigoris79** [comment]
Guys doesn't work to me to with firefox 56.0.2

Even with these two 
extensions.webextensions.remote
&
dom.event.clipboardevents.enabled
at true.

So can you please fix it?

**Comment by def00111** [comment]
@grigoris79 Can you list all installed add-ons? Maybe some add-on conflict?

**Comment by hackel** [comment]
Also does not seem to be working on FF57 on Android with out of process extensions enabled.

**Comment by joehillen** [comment]
FF57 Linux
`extensions.webextensions.remote = true`
`dom.event.clipboardevents.enabled = true`

It only works on some sites. For example, it works on Github, but nowhere else.

**Comment by joehillen** [comment]
This extension works instead. https://addons.mozilla.org/en-US/firefox/addon/copy-text-link/

**Comment by MichaelTunnell** [comment]
@joehillen I am using FF57 on Linux and this extension, from @def00111, works perfectly for me now. I have used it on dozens of sites without issue for about two weeks now.

`extensions.webextensions.remote = false` - I have this set to false which is the default in F57, it works fine.

`dom.event.clipboardevents.enabled = true` - this is the default in F57 so that is no need to change anything there.

Joe, please set the values back to default and test again.

**Comment by joehillen** [comment]
They were at the default before I found this issue.

**Comment by MichaelTunnell** [comment]
@joehillen please list the addons you are currently using as it may be a conflict with an addon.

**Comment by def00111** [comment]
> FF57 Linux
> extensions.webextensions.remote = true
> dom.event.clipboardevents.enabled = true
> 
> It only works on some sites. For example, it works on Github, but nowhere else.

Can you show me a site where it will not work?

**Comment by def00111** [comment]
https://github.com/def00111/copy-link-text/commit/d176428be89b86a1a5ca1ae6b3811eb5d8caa71a

**Comment by def00111** [comment]
Can you try new version?

**Comment by def00111** [comment]
Note: You need to reload the page when you install this add-on.

**Comment by def00111** [comment]
Please report, if it doesn't work for you.
