### ISSUE TITLE
Copies backslashes as two backslashes

### ISSUE THREAD

**Issue by bstidham** [def00111/copy-link-text#10]
Links like "\\\\a\\b\\c" are copied as "\\\\\\\\a\\\\b\\\\c"
On windows 10 in Firefox 69.0.3 64bit

**Comment by anewuser** [comment]
[Example: \a\b\c](https://example.org).

**Comment by def00111** [comment]
Fixed in 1.6.2.

**Comment by grahamperrin** [comment]
#13
