### ISSUE TITLE
1.6.5 broken in Waterfox G6.0.19

### ISSUE THREAD

**Issue by GTR8000** [def00111/copy-link-text#16]
1.6.5 broke functionality in Waterfox G6.0.19, which is based on Firefox 115 ESR. The Copy Link Text no long appear in the context menu.

Reverted back to 1.6.4 and the Copy Link Text once again appears in the context menu and works as it has for years.

**Comment by GTR8000** [comment]
@def00111

**Comment by def00111** [comment]
This add-on was only made for Firefox! I do not care for other browsers.
