### ISSUE TITLE
Backslashes are removed

### ISSUE THREAD

**Issue by bstidham** [def00111/copy-link-text#2]
I have a number of file system links that i use regularly in web pages
The file system links are windows urls and look like this: \\\\computername\\path\\to\\file
This removes any backslashes that aren't "escaped" so that the copied link looks like this: \\computernamepathtofile

**Comment by def00111** [comment]
https://github.com/def00111/copy-link-text/commit/d6b809e55b7c71f24d8efce0a6664252246055da

**Comment by bstidham** [comment]
@def00111 thanks. this is now working as expected.
