### ISSUE TITLE
Hotkey in menu

### ISSUE THREAD

**Issue by daregod** [def00111/copy-link-text#3]
There is possible to add a hotkey?
e.g "Copy link te&xt" for x as hotkey

**Comment by def00111** [comment]
We need to wait for this bug :(
https://bugzilla.mozilla.org/show_bug.cgi?id=1320462

**Comment by mboyd1** [comment]
bug is marked fixed in bugzilla.  +1 for this feature request!

**Comment by def00111** [comment]
Fixed in version 1.5.4.
